name: labcore-docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - nbsphinx
  - pandoc
  - ipykernel
  - linkify-it-py
  - h5py  # Not a doc requirement but the pip installation fails.